# Generated by Django 4.1.7 on 2023-03-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=50)),
                ('report_date', models.DateField()),
                ('report_data', models.TextField()),
            ],
        ),
    ]
