# Generated by Django 4.1.7 on 2023-03-16 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_seller_contact_seller_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales_record',
            old_name='product_name',
            new_name='product',
        ),
    ]
