# Generated by Django 4.1.7 on 2023-03-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_salesrecord_rename_seller_vendor_delete_sales_record_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='report',
        #     name='id',
        #     field=models.AutoField(default=1, primary_key=True, serialize=False),
        # ),
        # migrations.AlterField(
        #     model_name='report',
        #     name='report_type',
        #     field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=50),
        # ),
    ]
