# Generated by Django 4.1.7 on 2023-03-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_report_id_alter_report_report_type'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='report',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
    ]
