# Generated by Django 4.1.7 on 2023-03-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_report_id'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='report',
        #     name='id',
        # ),
        # migrations.AddField(
        #     model_name='report',
        #     name='report_id',
        #     field=models.AutoField(default=1, primary_key=True, serialize=False),
        # ),
    ]
