# Generated by Django 4.1.7 on 2023-03-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_remove_report_id_report_report_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=50)),
                ('report_date', models.DateField()),
                ('report_data', models.TextField()),
            ],
        ),
        # migrations.DeleteModel(
        #     name='Report',
        # ),
    ]
