# Generated by Django 4.1.7 on 2023-03-24 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_order_log_remove_orderitem_log_and_more'),
        ('reports', '0009_reportdata_delete_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.vendor')),
            ],
        ),
        # migrations.DeleteModel(
        #     name='Report',
        # ),
        migrations.DeleteModel(
            name='SalesRecord',
        ),
    ]
